Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "forwarded_port", guest: 19132, host: 19132
  config.vm.synced_folder "../bedrock-server-1.20.51.01", "/home/bedrock_server"
end
